<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BlockedStatusCheck"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="urn:sap-com:document:sap:rfc:functions"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/CreateOrUpdTrx"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/EchoStarSOA/SalesOrder/CreateOrUpdTrx"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/GTS/SalesOrder/BlockedStatusCheck">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/SalesOrder.wsdl"/>
                <oracle-xsl-mapper:rootElement name="_-SAPSLL_-API_6800_SYNCH_MASS.Response"
                                               namespace="urn:sap-com:document:sap:rfc:functions"/>
            </oracle-xsl-mapper:source>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/CreateOrUpdTrx.wsdl"/>
                <oracle-xsl-mapper:rootElement name="OutputParameters"
                                               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/CreateOrUpdTrx"/>
                <oracle-xsl-mapper:param name="CreateTrx_CreateOrUpdTrx_OutputVariable.OutputParameters"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/BlockedStatusCheck.wsdl"/>
                <oracle-xsl-mapper:rootElement name="BlockedStatusCheckOutputCollection"
                                               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BlockedStatusCheck"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAR 25 11:11:42 MDT 2016].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:param name="CreateTrx_CreateOrUpdTrx_OutputVariable.OutputParameters"/>
    <xsl:template match="/">
        <tns:BlockedStatusCheckOutputCollection>
            <tns:BlockedStatusCheckOutput>
                <tns:trx_id>
                    <xsl:value-of select="$CreateTrx_CreateOrUpdTrx_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_TRX_ID"/>
                </tns:trx_id>
                <xsl:for-each select="/ns0:_-SAPSLL_-API_6800_SYNCH_MASS.Response/RESULT_LEGAL_CONTROL/item">
                    <tns:status_text>
                        <xsl:value-of select="STATUS_TEXT"/>
                    </tns:status_text>
                     <tns:servic_text>
                        <xsl:value-of select="SERVIC_TEXT"/>
                    </tns:servic_text>
                </xsl:for-each>
               
            </tns:BlockedStatusCheckOutput>
        </tns:BlockedStatusCheckOutputCollection>
    </xsl:template>
</xsl:stylesheet>
