<wsdl:definitions
     name="BlockedStatusCheck"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GTS/SalesOrder/BlockedStatusCheck"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GTS/SalesOrder/BlockedStatusCheck"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/BlockedStatusCheck"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="BlockedStatusCheck_plt" >
    <plt:role name="BlockedStatusCheck_role" >
      <plt:portType name="tns:BlockedStatusCheck_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="BlockedStatusCheck_plt" >
    <plt:role name="BlockedStatusCheck_role" >
      <plt:portType name="tns:BlockedStatusCheck_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="BlockedStatusCheck_plt" >
    <plt:role name="BlockedStatusCheck_role" >
      <plt:portType name="tns:BlockedStatusCheck_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BlockedStatusCheck" schemaLocation="../Schemas/BlockedStatusCheck.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BlockedStatusCheck" schemaLocation="../Schemas/BlockedStatusCheck.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BlockedStatusCheck" schemaLocation="../Schemas/BlockedStatusCheck.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="BlockedStatusCheckInput_msg">
        <wsdl:part name="BlockedStatusCheckInput_msg" element="db:BlockedStatusCheckInput"/>
    </wsdl:message>
    <wsdl:message name="BlockedStatusCheckOutputCollection_msg">
        <wsdl:part name="BlockedStatusCheckOutputCollection" element="db:BlockedStatusCheckOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="BlockedStatusCheck_ptt">
        <wsdl:operation name="BlockedStatusCheck">
            <wsdl:input message="tns:BlockedStatusCheckInput_msg"/>
            <wsdl:output message="tns:BlockedStatusCheckOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
