<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="InsertCtMapErr" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GTS/SalesOrder/InsertCtMapErr" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GTS/SalesOrder/InsertCtMapErr" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/InsertCtMapErr" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="InsertCtMapErr_plt">
      <plt:role name="InsertCtMapErr_role">
         <plt:portType name="tns:InsertCtMapErr_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/InsertCtMapErr" schemaLocation="../Schemas/InsertCtMapErr_sp.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="args_in_msg">
      <wsdl:part name="InputParameters" element="db:InputParameters"/>
   </wsdl:message>
   <wsdl:portType name="InsertCtMapErr_ptt">
      <wsdl:operation name="InsertCtMapErr">
         <wsdl:input message="tns:args_in_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
